### ISSUE TITLE
Mouse hover and more

### ISSUE THREAD

**Issue by CAPTAiNHANDSOME** [fluddokt/opsu#103]
Please consider adding mouse hovering support (which Snapseed, Chrome and more app supports OTG mouse and S-Pen hover) so that we can connect it to an keyboard and mouse (or keyboard and Spen) and use Z,X keys to hit. And it would make this game great for Chromebooks which can run Android apps. Also having issues Playing beatmap sound effects wav files (Beatmap ID 400208) on Note4, running 6.0.1 MMB29K

**Comment by fluddokt** [comment]
Mouse Hovering should be fixed in 0.15.0a.

Yea. Since libgdx is unable to load those sound. So I'm not really sure what I can do.
