### ISSUE TITLE
Help with album covers/etc

### ISSUE THREAD

**Issue by kilometerman** [fluddokt/opsu#106]
whenever I move a folder for a song into the opsu song folder, my gallery gets filled with the individual album art. they're all in individual folders for each song, and moving them into one folder just makes it so they dont load into opsu.

any way to fix this? thanks for your work on the whole project by the way.

**Comment by flazep3** [comment]
Hey, try to put a .nomedia in your opsu folder (emulated/0/opsu/here) if your too lazy to make one, download here http://androidhost.org/get/Tz3Ns NOTE: MOVE this to opsu folder and add a dot (.) In front of the name by renaming it to .nomedia tell me if its fixed after you tried. Restart your phone to be sure

**Comment by kilometerman** [comment]
It worked, thanks for the help. Strange that I had to go in X-plore to do it though, since there was in fact a ".nomedia" file when I looked at it in the download manager. Thanks again.
