### ISSUE TITLE
I DOWNLOAD BEATMAPS BUT CAN'T USE THEM OR DOESNT SHOW UP ON THE PLAY MENU

### ISSUE THREAD

**Issue by JoltP** [fluddokt/opsu#111]
It keeps saying "you have no beatmaps download a new one" WHY :(

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sp7731gea_lm
FINGERPRINT: Huawei/MediaPad/hwt1701:4.4.2/HuaweiMediaPad/T1701uaV1R1C209B008:user/release-keys
HOST: wuheatculx00113
MODEL: T1 7.0
INCREMENTAL: C209B008
RELEASE: 4.4.2

**Comment by fluddokt** [comment]
You need to press "import all" after downloading.
Restarting should also work.
