### ISSUE TITLE
BEATMAPS STILL DOES NOT WORK

### ISSUE THREAD

**Issue by JoltP** [fluddokt/opsu#113]
I pressed the import all button after the download then i pressed back to check it. Beatmap was not there. I did the same thing again but i restarted the game. Still it doesnt work.
What am i doing wrong?
Amymore ideas to fix this problem?

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sp7731gea_lm
FINGERPRINT: Huawei/MediaPad/hwt1701:4.4.2/HuaweiMediaPad/T1701uaV1R1C209B008:user/release-keys
HOST: wuheatculx00113
MODEL: T1 7.0
INCREMENTAL: C209B008
RELEASE: 4.4.2

**Comment by itdelatrisu** [comment]
You probably downloaded a pack without any Standard beatmaps in it.  Unfortunately, there's no way to tell using some of these download servers' APIs unless we hit the osu! API, which I don't want to do.
