### ISSUE TITLE
Can't login to osu

### ISSUE THREAD

**Issue by MegaFish0527** [fluddokt/opsu#115]
It seems that I cannot login to my osu account, will this be later implemented?

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@66.0 AU@04.04.02.048.018 (CL@) (Qualcomm)
BOARD: MSM8610
FINGERPRINT: motorola/condor_tracfone/condor_cdma:4.4.4/KXC21.5-40/35:user/release-keys
HOST: ilclbld27
MODEL: XT830C
INCREMENTAL: 35
RELEASE: 4.4.4

**Comment by flazep3** [comment]
Really? That is not a bug AT ALL. Didn't you read the changelog?
