### ISSUE TITLE
Can't download beatmaps

### ISSUE THREAD

**Issue by lostinmusic222** [fluddokt/opsu#119]
[Type your description here. Feel free to delete the info below if it's not relevant.]

When I try to download a beatmap it says "could not establish connection to the server" even though I am connected to wifi. 
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65 (ARM)
BOARD: R1_HD
FINGERPRINT: BLU/R1_HD/R1_HD:6.0/MRA58K/1478669896:user/release-keys
HOST: C208
MODEL: R1 HD
INCREMENTAL: 1478669896
RELEASE: 6.0

**Comment by itdelatrisu** [comment]
Bloodcat is down, try switching download servers.
