### ISSUE TITLE
Servers for beatmap download are not online

### ISSUE THREAD

**Issue by meisjuan** [fluddokt/opsu#120]
The servers for beatmap downloading are offline. When i use Bloodcat it says could not establish connection. When i use other servers like YaS Online it will say error everytime i picked a beatmap to download.
The only way to download beatmap is to download it manually at the osu web page and and put the beatmap osz files in the import folder inside the opsu folder.

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-03rel0.dec36ba15c3f1bc697cb53aefb95b03e (ARM)
BOARD: universal7870
FINGERPRINT: samsung/on7xeltedd/on7xelte:6.0.1/MMB29K/G610FDXU1APL7:user/release-keys
HOST: SWHC3908
MODEL: SM-G610F
INCREMENTAL: G610FDXU1APL7
RELEASE: 6.0.1

**Comment by itdelatrisu** [comment]
There's nothing we can do here when those servers are down, sorry. :/  MengSky did change their API since the last release (see itdelatrisu/opsu@06370bd), and that'll be updated in the next release.  Mnetwork is still working right now.
