### ISSUE TITLE
can not download my music

### ISSUE THREAD

**Issue by erfireakaflypet** [fluddokt/opsu#121]
all the time i could not etablish connection to server

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 build 1.9@2204701 (Imagination Technologies)
BOARD: bbk89_cmcc_jb2
FINGERPRINT: vivo/bbk89_cmcc_jb2/bbk89_cmcc_jb2:4.2.1/JOP40D/1414577107:user/test-keys
HOST: compiler011
MODEL: vivo X1St
INCREMENTAL: eng.compiler.1414577107
RELEASE: 4.2.1

**Comment by itdelatrisu** [comment]
Those servers are down right now, nothing we can do.  Try using Mnetwork for now.
