### ISSUE TITLE
Song download issue 

### ISSUE THREAD

**Issue by Asumine** [fluddokt/opsu#122]
Only 1 server seems to work to download beatmaps/songs and then the other seem to just connection error. Also when I click on a song windows pop up and say something about an error then the screen goes black

**Comment by itdelatrisu** [comment]
The other servers are down, nothing we can do.  What's the error?

**Comment by Asumine** [comment]
Redownloaded the game and it no longer pops up

**Comment by itdelatrisu** [comment]
Great, thanks for the quick reply!
