### ISSUE TITLE
Can't download songs

### ISSUE THREAD

**Issue by crokanaw3322** [fluddokt/opsu#123]
Love osu so downloaded this been playing it for about 3 days and then all of a sudden I can no longer download beat maps,  it just says failed to download due to a connection error, no matter what server I use or what wi-fi/data connection I use. 

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: SC9830I
FINGERPRINT: samsung/j3xnltexx/j3xnlte:5.1.1/LMY47V/J320FNXXS0APL2:user/release-keys
HOST: SWDD6402
MODEL: SM-J320FN
INCREMENTAL: J320FNXXS0APL2
RELEASE: 5.1.1

**Comment by itdelatrisu** [comment]
All the servers really did just go down at the same time. :(  You can still download songs manually and copy them to your phone, and I think the Mnetwork server is still working (just slow).  There's a change in the MengSky API that will get updated in the next release here.
