### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Wojtaszek123** [fluddokt/opsu#124]
"Connection error" when I want to download beatmap. Working wifi.

---
**Version:** OpsuAnd0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@Idd51518bdf) (Qualcomm)
BOARD: msm8916
FINGERPRINT: lge/m216n_global_com/m216n:6.0/MRA58K/1630620076e17:user/release-keys
HOST: LGEACI5R5
MODEL: LG-K420
INCREMENTAL: 1630620076e17
RELEASE: 6.0

**Comment by itdelatrisu** [comment]
The download servers are all down, sorry.  Nothing we can do.
