### ISSUE TITLE
error due to conection issue 

### ISSUE THREAD

**Issue by ducanh100301** [fluddokt/opsu#125]
[Type your description here. Feel free to delete the info below if it's not relevant.]
When i download a song on opsu its said download failed due to a connection error although my Internet were fine and i tried all the server but it ain't working
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: LenovoTB3-710I
FINGERPRINT: Lenovo/LenovoTB3-710I/TB3-710I:5.1/LMY47I/TB3-710I_S000029_160318_ROW:user/release-keys
HOST: scmbuild
MODEL: Lenovo TB3-710I
INCREMENTAL: Lenovo_TB3-710I_S000029
RELEASE: 5.1

**Comment by itdelatrisu** [comment]
The download servers are down, sorry. :(
