### ISSUE TITLE
Opsu error

### ISSUE THREAD

**Issue by hgyg11** [fluddokt/opsu#126]
Hello! I had a download error and i didn't know what can i do with this... ,,download failed due to a connection error" Please tell me what can i do or fix it. 
Thanks for learn this.
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 (Vivante Corporation)
BOARD: PXA19xx
FINGERPRINT: samsung/coreprimeveltexx/coreprimevelte:5.1.1/LMY48B/G361FXXU1APA3:user/release-keys
HOST: SWDD6522
MODEL: SM-G361F
INCREMENTAL: G361FXXU1APA3
RELEASE: 5.1.1

**Comment by itdelatrisu** [comment]
All the download servers are down.  Sorry, nothing we can do. :(

**Comment by hgyg11** [comment]
Sad :(
