### ISSUE TITLE
Connection issue with songs!

### ISSUE THREAD

**Issue by RazorCheck** [fluddokt/opsu#127]
Hey, I'm trying to download Freedom Dive in the song area and when I try to it says Error connection to server failed and it says that to every song I try to download! PLZ help more fix this!
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: unknown
FINGERPRINT: RCA/RCT6773W22B/RCT6773W22B:5.0/LRX21M/1427286964:user/release-keys
HOST: tablet11.gyrodock.com:2300
MODEL: RCT6773W22B
INCREMENTAL: 1427286964
RELEASE: 5.0

**Comment by itdelatrisu** [comment]
All the download servers are down.  Sorry, nothing we can do. :(
