### ISSUE TITLE
Can't download songs from servers

### ISSUE THREAD

**Issue by ProJeCtAnima** [fluddokt/opsu#128]
As the title implies, It seems I can't download songs in the servers, giving me a pop-up "connection error" even though the internet is stable.

A quick fix is appreciated!
---
**Version:** 0.15.0b
**OS:** Linux (x86_64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 - Build 2.0.28075-ubit-Release (Intel)
BOARD: baylake
FINGERPRINT: acer/a1840_ww_gen1/ducati2hd:4.4.4/KTU84P/1442563038:user/release-keys
HOST: pandora01
MODEL: A1-840
INCREMENTAL: 1442563038
RELEASE: 4.4.4

**Comment by itdelatrisu** [comment]
The servers are down, nothing we can do. :(
