### ISSUE TITLE
Cant download song

### ISSUE THREAD

**Issue by OoyschesteroO** [fluddokt/opsu#129]
just cant download any song 

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-03dev0.ed32a5440f20c29503930f67988bdcc5 (ARM)
BOARD: universal7880
FINGERPRINT: samsung/a7y17ltexx/a7y17lte:6.0.1/MMB29K/A720FXXU1AQC2:user/release-keys
HOST: SWDD6007
MODEL: SM-A720F
INCREMENTAL: A720FXXU1AQC2
RELEASE: 6.0.1

**Comment by itdelatrisu** [comment]
It's not just you, all the servers are down. :(
