### ISSUE TITLE
opsu-android occasionally "misses" the first circle or slider

### ISSUE THREAD

**Issue by chong601** [fluddokt/opsu#13]
(TODO: add the maps that is affected, but other maps also happen to occur at random)
On the beginning of a play, opsu! will make a miss (on a circle) or misses the first slider head (only get 1x on the next slider tick or when reach slider end) even if I have pressed the note **on time**

It happens on quite a number of beatmaps and retrying the map doesn't solve the issue.

Occassionally, random tapping at the place of the 1st slider or circle will register as a hit **even** if the note is still 2-3s before it appears

**Comment by fluddokt** [comment]
I think I fixed this in 0.11.0a by removing !isLeadIn() in Game.java : gameKeyReleased
Since this allowed a press but not a release during leadIn.
I'm not sure how randomly tapping would have allowed it to hit before it appears though.
