### ISSUE TITLE
I cant download beatmaps on the game pls fix this asap thanks!!!!

### ISSUE THREAD

**Issue by Kaabin01** [fluddokt/opsu#130]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sc7730s
FINGERPRINT: samsung/core33gdd/core33g:4.4.4/KTU84P/G360HDDU0API1:user/release-keys
HOST: SWHD7422
MODEL: SM-G360H
INCREMENTAL: G360HDDU0API1
RELEASE: 4.4.4

**Comment by itdelatrisu** [comment]
The servers are down, nothing we can do.
