### ISSUE TITLE
Cant Download Beatmaps

### ISSUE THREAD

**Issue by AeroCrimson** [fluddokt/opsu#131]
Please help me in this problem I cant download any beatmaps the app says the connection is error but the internet is fast only the opsu app is saying that
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.346006f07df626299db0815d6206ce13 (ARM)
BOARD: mt6735
FINGERPRINT: lge/m253_global_com/m253:6.0/MRA58K/17004153951c3:user/release-keys
HOST: si-bldx37
MODEL: LG-K430
INCREMENTAL: 17004153951c3
RELEASE: 6.0

**Comment by itdelatrisu** [comment]
The servers are down, nothing we can do here. :(
