### ISSUE TITLE
can't download beatmaps

### ISSUE THREAD

**Issue by kidsbander2111** [fluddokt/opsu#132]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** OpsuAnd0.14.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.c2815c77377fd8176029d97c61eba4df (ARM)
BOARD: unknown
FINGERPRINT: Xiaomi/nikel/nikel:6.0/MRA58K/V8.0.3.0.MBFMIDG:user/release-keys
HOST: c3-miui-ota-bd05
MODEL: Redmi Note 4
INCREMENTAL: V8.0.3.0.MBFMIDG
RELEASE: 6.0[](url)
![screenshot_2017-04-01-19-37-50-135_fluddokt opsu android](https://cloud.githubusercontent.com/assets/26837795/24578800/ceb42de2-1712-11e7-8771-dc5d6d7d195a.png)

**Comment by itdelatrisu** [comment]
Bloodcat uses captchas now, so it doesn't work here anymore.  The other servers are down completely. :(
