### ISSUE TITLE
Cannot download any new beat maps?

### ISSUE THREAD

**Issue by notserP-ekarD** [fluddokt/opsu#133]
So I downloaded opsu! Earlier this month and I only downloaded one beatmap. Today when I hopped back on and tried to download some more, no matter which beat map it was, it would instantly say "download failed: no connection to server" (not exactly in those words but you get what im saying).

I really like that I can play osu! On my phone whenever, but if this is going to be reoccurring, I will be forced to uninstall.

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I86b60582e4) (Qualcomm)
BOARD: msm8996
FINGERPRINT: samsung/heroqlteuc/heroqlteatt:7.0/NRD90M/G930AUCS4BQC2:user/release-keys
HOST: SWHE7702
MODEL: SAMSUNG-SM-G930A
INCREMENTAL: G930AUCS4BQC2
RELEASE: 7.0

**Comment by itdelatrisu** [comment]
All the download servers are down, there's nothing we can do.  You can still download beatmaps manually and copy them into the `Import` folder.

**Comment by notserP-ekarD** [comment]
Ok thanks
