### ISSUE TITLE
Beatmap download error

### ISSUE THREAD

**Issue by flameswor25** [fluddokt/opsu#134]
Everytime I try to download a beatmap It says error can't download because it's not connected even though I am connected to the internet 
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@145.0 AU@  (GIT@Iae7096bdc4) (Qualcomm)
BOARD: FINANCIER
FINGERPRINT: ZTE/P817W01/financier:6.0.1/MMB29M/20161207.162110:user/release-keys
HOST: newsuper4
MODEL: Z957
INCREMENTAL: 20161207.162110
RELEASE: 6.0.1

**Comment by itdelatrisu** [comment]
The servers are down, sorry.
