### ISSUE TITLE
Beatmaos saying connection error

### ISSUE THREAD

**Issue by IfazAlam11** [fluddokt/opsu#138]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-03dev0.fccf31c657be3db1cb4cb1a0a6ac7320 (ARM)
BOARD: universal8890
FINGERPRINT: samsung/heroltebmc/heroltebmc:7.0/NRD90M/G930W8VLU2BQB6:user/release-keys
HOST: SWDD6604
MODEL: SM-G930W8
INCREMENTAL: G930W8VLU2BQB6
RELEASE: 7.0

**Comment by itdelatrisu** [comment]
The servers are down, sorry.
