### ISSUE TITLE
Need Help Regarding On The Songs 

### ISSUE THREAD

**Issue by KaitoShinte** [fluddokt/opsu#139]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: unknown
FINGERPRINT: lge/b2lds_global_com/b2lds:5.0.2/LRX22G/152532131cf4c:user/release-keys
HOST: si-rd10-bx37
MODEL: LG-D690
INCREMENTAL: 152532131cf4c
RELEASE: 5.0.2

Hello! I Have A Problem Regarding Downloading Songs In Opsu I Can't Download On Bloodcat and MengSky Can You Please Help Me When I Download A Song It Says Error I Love The Game Please Help Me And It's Not My Internet Connection I Can Download Songs Or Anything Very Fast

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
