### ISSUE TITLE
Cant download beatmapa

### ISSUE THREAD

**Issue by Miraie** [fluddokt/opsu#140]
[I cant download beatmaps through the direct download option it says "Download failed due to a connection error." And yes i already connect my device to internet.]

---
**Version:** 0.15.0b
**OS:** Linux (aarch64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@ (GIT@Ic8ede1fb34) (Qualcomm)
BOARD: msm8916
FINGERPRINT: Xiaomi/ido/ido:5.1.1/LMY47V/6.12.15:user/release-keys
HOST: c3-miui-ota-bd48.bj
MODEL: Redmi 3
INCREMENTAL: 6.12.15
RELEASE: 5.1.1

**Comment by lefkash** [comment]
I have the same error message >.> dunno wat to do about it

**Comment by lefkash** [comment]
oh and I have a oneplus 3 if that's something to note

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
