### ISSUE TITLE
Probleme de telechargrment beatmap

### ISSUE THREAD

**Issue by Gaturi1000** [fluddokt/opsu#141]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-03rel0.b8759509ece0e6dda5325cb53763bcf0 (ARM)
BOARD: universal7580
FINGERPRINT: samsung/a5xeltexx/a5xelte:6.0.1/MMB29K/A510FXXU3BPK4:user/release-keys
HOST: SWHE2610
MODEL: SM-A510F
INCREMENTAL: A510FXXU3BPK4
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
