### ISSUE TITLE
can't download song

### ISSUE THREAD

**Issue by rskingpvp** [fluddokt/opsu#142]
It's say error every song i want to download

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 (ARM)
BOARD: universal3475
FINGERPRINT: samsung/j2ltedx/j2lte:5.1.1/LMY47X/J200GUDXU2APL1:user/release-keys
HOST: SWDD5818
MODEL: SM-J200GU
INCREMENTAL: J200GUDXU2APL1
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
