### ISSUE TITLE
Bitmap download failure 

### ISSUE THREAD

**Issue by BlueTiNet** [fluddokt/opsu#145]
[when i try to download a bit map it says connection error. I tried with mobile data and wifi and both show the same error]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@I741a3d36ca) (Qualcomm)
BOARD: MSM8974
FINGERPRINT: Sony/D6503/D6503:6.0.1/23.5.A.1.291/2769308465:user/release-keys
HOST: BuildHost
MODEL: D6503
INCREMENTAL: 2769308465
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
