### ISSUE TITLE
Can't download any beatmap. It says download failed due to a connection error.

### ISSUE THREAD

**Issue by BeatriceGabriel** [fluddokt/opsu#146]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: ASUS_Z00VD
FINGERPRINT: asus/WW_Phone/ASUS_Z00VD:5.1/LMY47I/WW_Phone-12.1.0.51-20160825:user/release-keys
HOST: scmbuild
MODEL: ASUS_Z00VD
INCREMENTAL: WW_Phone-12.1.0.51-20160825
RELEASE: 5.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.

**Comment by BeatriceGabriel** [comment]
Omg, I should tell you early that I could download beatmaps a few days ago.
Thanks though :)
