### ISSUE TITLE
I cant download a beatmap

### ISSUE THREAD

**Issue by ServedX** [fluddokt/opsu#147]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 (ARM)
BOARD: universal5420
FINGERPRINT: samsung/ha3gxx/ha3g:5.0/LRX21V/N900XXSEBQC2:user/release-keys
HOST: SWDG9723
MODEL: SM-N900
INCREMENTAL: N900XXSEBQC2
RELEASE: 5.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
