### ISSUE TITLE
Beatmap download

### ISSUE THREAD

**Issue by Clarirated** [fluddokt/opsu#150]
Unable to download any beatmaps from the app. 

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.a6c0939b3050616905647b55b149c24b (ARM)
BOARD: full_tubads
FINGERPRINT: Sony/F3116/F3116:6.0/33.2.B.3.81/1413738821:user/release-keys
HOST: BuildHost
MODEL: F3116
INCREMENTAL: 1413738821
RELEASE: 6.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
