### ISSUE TITLE
Can't download songs

### ISSUE THREAD

**Issue by iasaf** [fluddokt/opsu#151]
Hello, i cant download the songs, rest of it is perfectly working 

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 build 1.10@2359475 (Imagination Technologies)
BOARD: universal5410
FINGERPRINT: samsung/ja3gxx/ja3g:5.0.1/LRX22C/I9500XXUHPK1:user/release-keys
HOST: SWHE0707
MODEL: GT-I9500
INCREMENTAL: I9500XXUHPK1
RELEASE: 5.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
