### ISSUE TITLE
"Error occured due to connection error"

### ISSUE THREAD

**Issue by xraykam** [fluddokt/opsu#152]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0

Just downloaded this for the first time so annoying.

**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@  (CL@) (Qualcomm)
BOARD: MSM8226
FINGERPRINT: samsung/milletlteuc/milletlteatt:5.1.1/LMY47X/T337AUCS2BOH5:user/release-keys
HOST: SWHE8822
MODEL: SAMSUNG-SM-T337A
INCREMENTAL: T337AUCS2BOH5
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
