### ISSUE TITLE
I can't download the song!

### ISSUE THREAD

**Issue by snacksgirl** [fluddokt/opsu#155]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@05.01.00.032.018 (GIT@I856e09677e) (Qualcomm)
BOARD: msm8916
FINGERPRINT: samsung/rossaltedv/rossaltexsa:5.1.1/LMY48B/G360GDXS1BPI4:user/release-keys
HOST: SWDD3022
MODEL: SM-G360G
INCREMENTAL: G360GDXS1BPI4
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
