### ISSUE TITLE
Beatmaps wont download

### ISSUE THREAD

**Issue by romet38** [fluddokt/opsu#156]
Ive downloaded the app and then tried to download some beatmps but it kept saying i got connection error and im using mobile data.
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: SC9830I
FINGERPRINT: samsung/j3xnltexx/j3xnlte:5.1.1/LMY47V/J320FNXXS0APL1:user/release-keys
HOST: SWDD6322
MODEL: SM-J320FN
INCREMENTAL: J320FNXXS0APL1
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
