### ISSUE TITLE
Can't download maps!

### ISSUE THREAD

**Issue by UnravelMay** [fluddokt/opsu#157]
Hi, when I download a map from opsu! It says error below the maps name and tells me download failed due to a connection error. I have restarted the app, my tablet and cleared the data from the app and tried lots of times with different maps but I can't download. When I tap the play music icon the music plays so yes it's connected to WiFi but I can't​download maps. Here's a screenshot.  Thanks! @fluddokt @itdelatrisu 
![screenshot_2017-05-02-13-56-49](https://cloud.githubusercontent.com/assets/28296949/25618576/6abf28ec-2f3f-11e7-8895-2f6e373684c2.png)

**Comment by DZAK1** [comment]
That is my problem also.

**Comment by dubbylove** [comment]
Wow asking this question is useless, i have the same probleme, even hundreds and they still haven't fixed it...

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
