### ISSUE TITLE
I cant download songs

### ISSUE THREAD

**Issue by Theimpossible** [fluddokt/opsu#158]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sp7731gea_hd
FINGERPRINT: Philips/S337/S337_BG:5.1/LMY47D/ateam503071651:user/release-keys
HOST: ateam
MODEL: Philips S337
INCREMENTAL: eng.ateam5.20160307.165013
RELEASE: 5.1

**Comment by Theimpossible** [comment]
I have a conection error and i cant download songs

**Comment by BlockHead007** [comment]
Maybe the server doesn't working?

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
