### ISSUE TITLE
CONNECTION ERROR

### ISSUE THREAD

**Issue by Dreymur** [fluddokt/opsu#160]
This used to work before, now it's broken. Everytime I try to download a song, it says to download failed due to a connection error. I've tried downloading from different servers, reinstalling, and installing older versions, but none of that seems to work. I just really want to play this but this error makes it impossible.

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@05.01.00.032.018 (GIT@I856e09677e) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: samsung/cprimeltemtr/cprimeltemtr:5.1.1/LMY47X/G360T1UVU1APG2:user/release-keys
HOST: SWDD6306
MODEL: SM-G360T1
INCREMENTAL: G360T1UVU1APG2
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
