### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by AndroidL2002** [fluddokt/opsu#161]
Hello pls. Fix the connection error..i am having an strong wifi connection..pls fix it tnx

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia10634f51b) (Qualcomm)
BOARD: msm8916
FINGERPRINT: lge/k5_global_com/k5:6.0.1/MMB29M/16193161182fa:user/release-keys
HOST: CLD-BLD3-VM1-16
MODEL: LG-K500
INCREMENTAL: 16193161182fa
RELEASE: 6.0.1

**Comment by HertKRisTOf12** [comment]
me too pls

**Comment by Jr234koolaid** [comment]
Same

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
