### ISSUE TITLE
Dosen't dowland

### ISSUE THREAD

**Issue by HertKRisTOf12** [fluddokt/opsu#162]
I go to the DOWLAND section and try to dowland any kind of beatmap but it dosen't do anything it just write connection error but i have good internet connection
---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@I741a3d36ca) (Qualcomm)
BOARD: msm8909
FINGERPRINT: Lenovo/YT3-850F/YT3-850F:6.0.1/MMB29M/YT3-850F_USR_S112_170317_Q1241_ROW:user/release-keys
HOST: ubuntu
MODEL: Lenovo YT3-850F
INCREMENTAL: YT3-850F_S000112_170317_ROW
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
