### ISSUE TITLE
Beatmap download error

### ISSUE THREAD

**Issue by PSbezP** [fluddokt/opsu#163]
When i wanna download a beatmap it says that there is connection error.

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@05.00.00.042.005 (CL@) (Qualcomm)
BOARD: MSM8226
FINGERPRINT: lge/e8lte_global_com/e8lte:5.0.2/LRX22G/1523808437809:user/release-keys
HOST: LGEACI5R2
MODEL: LG-V490
INCREMENTAL: 1523808437809
RELEASE: 5.0.2

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
