### ISSUE TITLE
Can't download songs

### ISSUE THREAD

**Issue by TheClichedGam3r** [fluddokt/opsu#165]
When attenpting to download beatmaps, it just says network error. When I manually download it and move it to the folder, it doesn't register.

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I86b60582e4) (Qualcomm)
BOARD: msm8996
FINGERPRINT: samsung/hero2qltespr/hero2qltespr:7.0/NRD90M/G935PVPU4BQD2:user/release-keys
HOST: SWDG9705
MODEL: SM-G935P
INCREMENTAL: G935PVPU4BQD2
RELEASE: 7.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.

Moving it should have worked if you moved .osz to the "opsu/import" directory or already extracted to "opsu/songs" but does require restarting the app.
