### ISSUE TITLE
Opsu bloodcat download error

### ISSUE THREAD

**Issue by derlonlon** [fluddokt/opsu#166]
When I try to download a beatmap an error message appears but I can hear the song preview

---
**Version:** 0.15.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@66.0 AU@04.04.02.006.082 (CL@) (Qualcomm)
BOARD: MSM8226
FINGERPRINT: htc/htc_europe/htc_memul:4.4.2/KOT49H/405590.2:user/release-keys
HOST: ABM023
MODEL: HTC One mini 2
INCREMENTAL: 405590.2
RELEASE: 4.4.2

**Comment by AsrielTW** [comment]
This is because bloodcat added a "Anti Robot"System

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
