### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Jr234koolaid** [fluddokt/opsu#167]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@  (GIT@) (Qualcomm)
BOARD: msm8916
FINGERPRINT: motorola/osprey_sprint/osprey_cdma:5.1.1/LPI23.72-32-S.28.5/6:user/release-keys
HOST: ilclbld32
MODEL: MotoG3
INCREMENTAL: 6
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.

**Comment by Jr234koolaid** [comment]
Thank you for putting the new server, Now I have more music I like to
download!

On Sep 4, 2017 10:13 PM, "fluddokt" <notifications@github.com> wrote:

Changed the default download server in 0.16.0a and Bloodcat option will now
open to the download page instead.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fluddokt/opsu/issues/167#issuecomment-327060730>, or mute
the thread
