### ISSUE TITLE
Why i'm cannot download song with mobile data

### ISSUE THREAD

**Issue by Sh1NZz** [fluddokt/opsu#171]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@05.01.00.016.029 (CL@) (Qualcomm)
BOARD: MSM8610
FINGERPRINT: asus/WW_Phone/ASUS_X014D_2:5.1.1/LMY47V/12.2.5.5-20160517:user/release-keys
HOST: ch-ubuntu-buildsrv34
MODEL: ASUS_X014D
INCREMENTAL: WW_Phone-12.2.5.5-20160517
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
