### ISSUE TITLE
Cant download beatmap,get a error message that says download failed due to a connection error

### ISSUE THREAD

**Issue by soppentran** [fluddokt/opsu#172]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r12p1-03dev0.228ab63cced004f840e7dd47b762a1d0 (ARM)
BOARD: universal8890
FINGERPRINT: samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQD7:user/release-keys
HOST: SWHE7715
MODEL: SM-G930F
INCREMENTAL: G930FXXU1DQD7
RELEASE: 7.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
