### ISSUE TITLE
Download failed due to a connection error.

### ISSUE THREAD

**Issue by KorVron** [fluddokt/opsu#173]
Hello,

I'm currently experiencing an issue with opsu in that I am unable to download songs, attempting to do so results in the error pictured.  I'm using the most recent version of opsu and I am currently running android nougat under the lineage OS ROM.

Are there any fixes available for this?  Please and thank you.
![tmp_31955-screenshot_20170605-232632413505591](https://cloud.githubusercontent.com/assets/16406828/26812629/dff3eef0-4a46-11e7-98d5-84c375b4f092.png)

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@127.0 AU@  (GIT@I96aee987eb) (Qualcomm)
BOARD: MSM8960
FINGERPRINT: samsung/lt02ltespr/lt02ltespr:4.4.2/KOT49H/T217SVPUBOH1:user/release-keys
HOST: phenom.zifnab.net
MODEL: SM-T217S
INCREMENTAL: 92172b0338
RELEASE: 7.1.2

**Comment by Lyonlancer5** [comment]
From the picture, I take that you're using Bloodcat as the download server. It's a known issue: https://github.com/itdelatrisu/opsu/issues/277

> Bloodcat uses captchas

Try the other servers instead (such as MengSky or Mnetwork)

**Comment by TheRealSinister** [comment]
None of them work

**Comment by GreyMariGaming** [comment]
https://github.com/itdelatrisu/opsu/issues/290

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
