### ISSUE TITLE
Beatmaps 

### ISSUE THREAD

**Issue by TheRealSinister** [fluddokt/opsu#174]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@I86b60582e4) (Qualcomm)
BOARD: msm8996
FINGERPRINT: samsung/hero2qltespr/hero2qltespr:7.0/NRD90M/G935PVPS4BQE1:user/release-keys
HOST: SWDG4513
MODEL: SM-G935P
INCREMENTAL: G935PVPS4BQE1
RELEASE: 7.0

I was able to download beatmaps before now I'm just getting error every time now

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
