### ISSUE TITLE
Can't download Error

### ISSUE THREAD

**Issue by DOoPiNHD** [fluddokt/opsu#175]
I can only download on Mnetwork but the rest doesn't let me download it says Error or Failed due to Connection Error.

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-03rel0.dec36ba15c3f1bc697cb53aefb95b03e (ARM)
BOARD: universal7870
FINGERPRINT: samsung/j7xeltedx/j7xelte:6.0.1/MMB29K/J710GNDXU1APF2:user/release-keys
HOST: SWDD5018
MODEL: SM-J710GN
INCREMENTAL: J710GNDXU1APF2
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
