### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by DaveSilvers** [fluddokt/opsu#176]
I can't download the songs,my Internet was good but can't download

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 v1.r7p0-02rel0.c2815c77377fd8176029d97c61eba4df (ARM)
BOARD: unknown
FINGERPRINT: Xiaomi/nikel/nikel:6.0/MRA58K/V8.0.3.0.MBFMIDG:user/release-keys
HOST: c3-miui-ota-bd05
MODEL: Redmi Note 4
INCREMENTAL: V8.0.3.0.MBFMIDG
RELEASE: 6.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
