### ISSUE TITLE
Cant download beatmaps

### ISSUE THREAD

**Issue by Ghaylan** [fluddokt/opsu#177]
Always connection error when downloading beatmaps even when wifi and cellular data is on

---
**Version:** 0.15.0b
**OS:** Linux (x86_64)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 build 1.4@3283119 (Imagination Technologies)
BOARD: moorefield
FINGERPRINT: asus/WW_Z00A/Z00A:5.0/LRX21V/2.20.40.174_20160310_4150_user:user/release-keys
HOST: fdc-12-jenkins
MODEL: ASUS_Z00AD
INCREMENTAL: WW_Z00A-WW_2.20.40.174_20160310_4150_user_rel-user-20160310
RELEASE: 5.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
