### ISSUE TITLE
Error downloading maps

### ISSUE THREAD

**Issue by PinguMLG** [fluddokt/opsu#179]
When i try to download a map says error downloading due to connection error

**Comment by Sthriller** [comment]
Try this
On top of beatmap downloads there is an option that says 'bloodcat'. Change that setting to 'Mnetwork'...

**Comment by tdunham99** [comment]
@Sthriller Tried that, didn't work. would installing beatmaps manually be the trick?

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.

Putting .osz into "opsu/Import" or extracted packs into "opsu/Songs" was also an option.
