### ISSUE TITLE
Can't play more beatmaps

### ISSUE THREAD

**Issue by RyuruKakitashi** [fluddokt/opsu#180]
I've downloaded 30+ Beatmaps and i opened the game and it says i have the 30+ beatmaps but when i pressed the play button, there's just like 8 beatmaps... Help me please ;-;

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@ (GIT@Ia10634f51b) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: samsung/j5xnltedx/j5xnlte:6.0.1/MMB29M/J510GNDXU2AQE2:user/release-keys
HOST: SWDD5515
MODEL: SM-J510GN
INCREMENTAL: J510GNDXU2AQE2
RELEASE: 6.0.1

**Comment by RyuruKakitashi** [comment]
And i downloaded all those beatmaps on osu cuz the download thing doesn't work.

**Comment by flaze216** [comment]
Some of them does not have osu! Gamemode. Lock this

**Comment by fluddokt** [comment]
Yeah opsu only takes osu!standard beatmaps also you might be counting songs since there are usually more than 1 beatmap (as in for each difficulty is 1 beatmap) for a song.
