### ISSUE TITLE
cant download any songs keeos saying network error but my network works fine

### ISSUE THREAD

**Issue by Ricsern** [fluddokt/opsu#187]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 v1.r15p0-00rel0.68b65ac7cf15907aeb95fa944f39eef2 (ARM)
BOARD: universal7420
FINGERPRINT: samsung/nobleltextc/noblelte:7.0/NRD90M/N9208XXU3CQE1:user/release-keys
HOST: SWDD5608
MODEL: SM-N9208
INCREMENTAL: N9208XXU3CQE1
RELEASE: 7.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
