### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by JustSomeUsername123** [fluddokt/opsu#188]
Hi. I wanted to play some osu, but since my other computer doesn't really work, I got opsu. I went to download a song, but it said failed due to a connection error. Opsu worked before, but, it's like as if it's now flipping the bird at me now. Help?

---
**Version:** 0.15.0b
**OS:** ChromeOS 59.0.3071.91 (Android Lollipop)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 Mesa 12.1.0-devel (git-5b173c57d1) (Intel Open Source Technology Center)
BOARD: cyan
FINGERPRINT: google/cyan/cyan_cheets:6.0.1/R59-9460.60.0/4059099:user/release-keys
HOST: vped8.mtv.corp.google.com
MODEL: Acer Chromebook R11 (CB5-132T / C738T)
INCREMENTAL: 4059099
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.

**Comment by JustSomeUsername123** [comment]
okay. thanks :)
