### ISSUE TITLE
Could not save replay data.

### ISSUE THREAD

**Issue by stmeao** [fluddokt/opsu#189]
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@  (GIT@) (Qualcomm)
BOARD: Y560-L01
FINGERPRINT: HUAWEI/Y560-L01/HWY560-L:5.1.1/HUAWEIY560-L01/C577B047:user/release-keys
HOST: yep
MODEL: HUAWEI Y560-L01
INCREMENTAL: C577B047
RELEASE: 5.1.1

**Error:** `Could not save replay data.`
**Stack trace:**
```
java.nio.charset.UnmappableCharacterException: Length: 1
	at java.nio.charset.CharsetEncoder.checkCoderResult(CharsetEncoder.java:282)
	at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:263)
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:343)
```

**Comment by fluddokt** [comment]
Hopefully fixed in 0.16.0b
