### ISSUE TITLE
I cant download beatmaps

### ISSUE THREAD

**Issue by kittengitgirl** [fluddokt/opsu#191]
[Type your description here. Feel free to delete the info below if it's not relevant.]
I ts says I have no internet and I do have a internet connection!!!! PLZ FIX!!!!!
---
**Version:** 0.15.0b
**OS:** Kindle OS (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.1 build 1.4@3573678 (Imagination Technologies)
BOARD: ariel
FINGERPRINT: Amazon/full_ariel/ariel:5.1.1/LVY48F/20.5.7.9_user_579225620:user/release-keys
HOST: 14-use1a-b-34
MODEL: KFARWI
INCREMENTAL: 20.5.7.9_user_579225620
RELEASE: 5.1.1

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
