### ISSUE TITLE
Can't download any songs

### ISSUE THREAD

**Issue by TheVicBro** [fluddokt/opsu#194]
Whenever I try to download a song, I just keep getting the error "Download failed due to a connection error"

---
**Version:** 0.15.0b
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@Idb2b4cb785) (Qualcomm)
BOARD: angler
FINGERPRINT: google/angler/angler:7.1.2/N2G48B/4073501:user/release-keys
HOST: wpix5.hot.corp.google.com
MODEL: Nexus 6P
INCREMENTAL: 4073501
RELEASE: 7.1.2

**Comment by Cuptaincapcake** [comment]
I am having the same problem

**Comment by Zukoia** [comment]
You can manually put a beatmap (.osk file) into the game:

1. Download the beatmap file you want (.osk) from https://osu.ppy.sh (you may need to create an account)
2. Put it in internal storage/opsu/Import folder
3. Reopen the game. The song should be installed

That's just a temporary solution I found. I hope it helps

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
