### ISSUE TITLE
Sou

### ISSUE THREAD

**Issue by netanel7150** [fluddokt/opsu#196]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@140.0 AU@  (GIT@Ia10634f51b) (Qualcomm)
BOARD: MSM8974
FINGERPRINT: samsung/kltexx/klte:6.0.1/MMB29M/G900FXXU1CPI8:user/release-keys
HOST: SWHC3607
MODEL: SM-G900F
INCREMENTAL: G900FXXU1CPI8
RELEASE: 6.0.1

**Comment by fluddokt** [comment]
?
