### ISSUE TITLE
I can't download osu music

### ISSUE THREAD

**Issue by JoeysdaNeko** [fluddokt/opsu#199]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@100.0 AU@05.01.01.032.053 (GIT@Ic8ede1fb34) (Qualcomm)
BOARD: MSM8916
FINGERPRINT: samsung/j3xproltezc/j3xproltechn:5.1.1/LMY47X/J3119XXU1APK1:user/release-keys
HOST: SWDD6811
MODEL: SM-J3119
INCREMENTAL: J3119XXU1APK1
RELEASE: 5.1.1

HOW I DOWNLOAD OSU MUSIC I CANT DOWNLOAD BECAUSE ERROR

**Comment by Zukoia** [comment]
You can manually put a beatmap (.osk file) into the game:
1. Download the beatmap file you want (.osk) from https://osu.ppy.sh (you may need to create an account)
2. Put it in internal storage/opsu/Import folder
3. Reopen the game. The song should be installed

That's a temporary solution I found. I hope the dev will work on the issue soon.

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
