### ISSUE TITLE
Won't import a song that I downloaded

### ISSUE THREAD

**Issue by Jr234koolaid** [fluddokt/opsu#202]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.15.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@Id9e7eae3da) (Qualcomm)
BOARD: msm8953
FINGERPRINT: motorola/potter/potter:7.0/NPNS25.137-33-5/5:user/release-keys
HOST: ilclbld85
MODEL: Moto G (5) Plus
INCREMENTAL: 5
RELEASE: 7.0

**Comment by fluddokt** [comment]
Put .osz into "opsu/import" or extracted into "opsu/songs".
then restart.
