### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by FireeFreak** [fluddokt/opsu#203]
I downloaded this game with Arc Welder but i'm in the application but when i try to download a song or a beatmap it would say "Download failed due to a connection error" idk if it's my wi-fi or maybe just a bug please fix it if it is a bug.
---
**Version:** 0.15.0b
**OS:** nacl (x86)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 Chromium (Chromium)
BOARD: bare_metal_i686
FINGERPRINT: chromium/arc/bare_metal_i686:5.0/54.5021.629.0/54.5021.629.0:user/release-keys
HOST: build111-m7.golo.chromium.org
MODEL: App Runtime for Chrome Dev
INCREMENTAL: 54.5021.629.0
RELEASE: 5.0

**Comment by fluddokt** [comment]
Changed the default download server in 0.16.0a and Bloodcat option will now open to the download page instead.
