### ISSUE TITLE
Hexide Server is Online

### ISSUE THREAD

**Issue by GreyMariGaming** [fluddokt/opsu#209]
Could you put back the hexide server back? It is working now.Tested and working. And Could you fix minework's search issue? You can put only one word.
![screenshot_20170916_145933](https://user-images.githubusercontent.com/28551384/30510048-ce2575aa-9aef-11e7-9d7d-1422f1bebc59.jpg)
![screenshot_20170916_145920](https://user-images.githubusercontent.com/28551384/30510046-ce124a66-9aef-11e7-9fd1-c2db40782146.jpg)
![screenshot_20170916_145914](https://user-images.githubusercontent.com/28551384/30510047-ce1ae662-9aef-11e7-91d9-01363f7b67e2.jpg)

**Comment by fluddokt** [comment]
re added and fixed
