### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Tegra3** [fluddokt/opsu#211]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: A7600-F
FINGERPRINT: Lenovo/A7600-F/A7600-F:4.4.2/KOT49H/A7600F_A442_000_022_140829_ROW:user/release-keys
HOST: vBuild1LVP0
MODEL: Lenovo A7600-F
INCREMENTAL: A7600F_A442_000_022_140829_ROW
RELEASE: 4.4.2

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
