### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by wrhutton** [fluddokt/opsu#212]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: rct6773w22
FINGERPRINT: RCA/RCT6773W22/RCT6773W22:4.4.2/KOT49H/1403615884:user/release-keys
HOST: think
MODEL: RCT6773W22
INCREMENTAL: 1401-V01
RELEASE: 4.4.2

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
