### ISSUE TITLE
Video doesn't play nor do pictures change In the old version some people said it worked.

### ISSUE THREAD

**Issue by Shiroyuki-z** [fluddokt/opsu#215]
[Type your description here. Feel free to delete the info below if it's not relevant.]

---
**Version:** 0.16.0a
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@145.0 AU@  (GIT@Ia3ef73d9d4) (Qualcomm)
BOARD: QC_Reference_Phone
FINGERPRINT: vivo/1606/1606:6.0.1/MMB29M/compiler09132117:user/release-keys
HOST: compiler026
MODEL: vivo 1606
INCREMENTAL: eng.compiler.20170913.211434
RELEASE: 6.0.1

**Comment by GreyMariGaming** [comment]
https://github.com/fluddokt/opsu/issues/210

**Comment by GreyMariGaming** [comment]
https://github.com/fluddokt/opsu/issues/210

**Comment by GreyMariGaming** [comment]
Some says that it causes lag to android.Correct me if I'm wrong but Maybe it doesnt support it anymore?
