### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by RayyaPen** [fluddokt/opsu#216]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: aupres_row
FINGERPRINT: Lenovo/aupres_row/A850_ROW:4.2.2/JDQ39/A850_ROW_S127_140303.1393843064:user/release-keys
HOST: nj-bs2
MODEL: Lenovo A850
INCREMENTAL: A850_ROW_S127_140303
RELEASE: 4.2.2

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
