### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by summerqp** [fluddokt/opsu#218]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@84.0 AU@  (CL@) (Qualcomm)
BOARD: 404KC
FINGERPRINT: KYOCERA/404KC/404KC:4.4.4/108.0.2c10/108.0.2c10:user/release-keys
HOST: KYOCERA
MODEL: 404KC
INCREMENTAL: 108.0.2c10
RELEASE: 4.4.4

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
