### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by Crisjay** [fluddokt/opsu#219]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: sc7730s
FINGERPRINT: samsung/grandneove3gxx/grandneove3g:4.4.4/KTU84P/I9060IXXS0AQC2:user/release-keys
HOST: SWDD5705
MODEL: GT-I9060I
INCREMENTAL: I9060IXXS0AQC2
RELEASE: 4.4.4

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
