### ISSUE TITLE
sliders issue

### ISSUE THREAD

**Issue by LuisFellp** [fluddokt/opsu#220]
[hey man! i have one bug on sliders, the sliders is going out of screen and i can't touch on them, please fix it]

---
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@145.0 (GIT@Id9e7eae3da) (Qualcomm)
BOARD: msm8937
FINGERPRINT: motorola/cedric/cedric:7.0/NPPS25.137-33-10/10:user/release-keys
HOST: ilclbld28
MODEL: Moto G (5)
INCREMENTAL: 10
RELEASE: 7.0

**Comment by fluddokt** [comment]
Added an option to change the playfield scaling in 0.16.1a so that if objects are going out of screen change that closer to 1.
