### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by GhostGamerX** [fluddokt/opsu#223]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.0 V@45.0 AU@  (CL@4169980) (Qualcomm)
BOARD: MSM8960
FINGERPRINT: samsung/jflteuc/jflteatt:4.3/JSS15J/I337UCUEMK2:user/release-keys
HOST: R0304-06
MODEL: SAMSUNG-SGH-I337
INCREMENTAL: I337UCUEMK2
RELEASE: 4.3

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
