### ISSUE TITLE
Help Getting the texture name for a custom skin I'm making

### ISSUE THREAD

**Issue by GreyMariGaming** [fluddokt/opsu#224]
Could you help me find the filename for the texture in the scoreboard? like the scoreboard?

This the normal skin
![screenshot_20171102_081505](https://user-images.githubusercontent.com/28551384/32303880-66ba6c14-bfa6-11e7-913f-a8f0db46e170.jpg)
This is my custom skin.
![screenshot_20171102_081429](https://user-images.githubusercontent.com/28551384/32303881-66fc6d3a-bfa6-11e7-97bf-60e2df673b0a.jpg)

**Comment by GreyMariGaming** [comment]
also most of the skin of cookiezi doesnt work.. like the spinner backround

**Comment by fluddokt** [comment]
Opsu doesn't use a texture for the scoreboard.
So you can't really change it I guess.

**Comment by flazepe** [comment]
Well, it uses menu-button-background.png but it's kind of useless to change it if you ask me.

**Comment by GreyMariGaming** [comment]
ohhh! That's why when i port my skin to osu! it also uses that. 
I get it now! thanks!
