### ISSUE TITLE
** Uncaught Exception! **

### ISSUE THREAD

**Issue by ItzNetMidPower** [fluddokt/opsu#227]
**Version:** 0.16.0b
**OS:** Linux (armv7l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 (ARM)
BOARD: aux
FINGERPRINT: Lenovo/aux/A850:4.2.2/JDQ39/A850_S203_140208.:user/release-keys
HOST: xmws46
MODEL: Lenovo A850
INCREMENTAL: A850_S203_140208
RELEASE: 4.2.2

**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag
	at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)
```

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
