### ISSUE TITLE
Incredibly slow touch response

### ISSUE THREAD

**Issue by hypixus** [fluddokt/opsu#230]
Device: Xiaomi Redmi Note 4 Global, 4/64 Snapdragon.
Version: latest release.
Issue: cursor movement is heavily behind android's touchscreen read(comparison between system cursor from programmers' settings and opsu!'s).
When: literally always. Frame rate is not the issue - steady 59-61.

Please consider looking whether this system is capable of direct touchscreen read like Windows(I don't know much about android yet UWP is familiar to me). It makes >6 stars maps unplayable, on 5 stars it causes ~10% account loss.

Thanks for any help.

**Comment by fluddokt** [comment]
Yea I don't think there is a way to reduce the delay, but it should play fine still as long as the offset is correct. You can always disable the cursor if it bugs you.
