### ISSUE TITLE
Spinner glitch on Android

### ISSUE THREAD

**Issue by Hydrixel** [fluddokt/opsu#24]
It Fills so slow, and it laggs and stops spinning every second.... :(

**Comment by SoonDead** [comment]
can confirm this on android 5.0.0 galaxy s4.

Cannot do the simplest spinners. This pretty much kills the game, so i still need to use osu!droid

An autospinner feature would be nice to have for mitigation.

**Comment by Hydrixel** [comment]
I use the autospinner in the mods tab... but feels unfair tho, but on my
other phone it works fine... maybe due to ram???

**Comment by Retalyx** [comment]
I had the same problem and I think it's because of the default Opsu skin, when I tried other skins, some of them fixed the spinners problem

**Comment by fluddokt** [comment]
Added in option to disable some spinner UI elements, hopefully this helps.

**Comment by SoonDead** [comment]
Holy crap, never expected this project to be revived (and this fixed)!

Time to reinstall this game I guess :)

**Comment by Retalyx** [comment]
Never expected too :D Nice
