### ISSUE TITLE
java.lang.NoSuchMethodError: java.util.Locale.forLanguageTag at itdelatrisu.opsu.replay.Replay$1.run(Replay.java:335)

### ISSUE THREAD

**Issue by ThePotatoDuke** [fluddokt/opsu#245]
This error shows up whenever I complete a song
I'm using a Samsung Galaxy Tab E    SM-T560
4.4.4 android version
Also hit sounds disappeared

**Comment by Yuuhei** [comment]
Mine too. always showing up every time and any beatmaps.
Samsung Galaxy J1 Ace SM-J110H, 
android 4.4.4
[opsu.log](https://github.com/fluddokt/opsu/files/1866245/opsu.log)

**Comment by Yuuhei** [comment]
**Update**
That error *seems* only *affects* devices 4.x and lower. Tested on my main phone Samsung SM-G532F (Grand Prime Plus or J2 Prime), 6.0.1 android version and the error is not appearing anymore.

Device tested with no errors:

Cloudfone Excite Prime
MT6592M 8 x 1.4GHZ
2GB RAM
Mali 450 / GLES 2.0

Samsung Galaxy Grand Prime Plus (more known as Galaxy J2 Prime)
MT6737T 4 x 1.4GHZ
1.5GB RAM
Mali T720-MP2 / GLES 3.1

Samsung Galaxy S4 GT-I9505
SD600 4 x 1.9GHZ
2GB RAM
Adreno 320 / GLES 3.0

only in my old phone with 4.4.4, that error keeps appearing.

(Sorry for my bad english lol)

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a
