### ISSUE TITLE
“local beatmap offset set to xxms” appears unexpected

### ISSUE THREAD

**Issue by Sodium-Aluminate** [fluddokt/opsu#247]
（my English is very , very poor so I put Chinese after that）
（英文太烂，补个中文orz）

press fingerprint while playing , “local beatmap offset set to xxms”appeared
玩的时候   按到 指纹 ， 出现 提示

maybe the “fingerprint” key have something similar with another key？
大概 是 它和调节延迟的按键重复了？

how can I disable it
怎么办......

device: redmi note 4x （mido）
设备：红米note4x

system: lineageOS 14.1-20180222-NIGHTLY-mido （Android 7.1.2）
系统：Los  14.1

(magisk was installed , but it cann't affact that......I guess)
（装了magisk，但应该不会影响......吧？）

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a.

**Comment by Sodium-Aluminate** [comment]
thanks
