### ISSUE TITLE
"local beatmap offset set" message appears unexpected when i touch on fingerprint sensor

### ISSUE THREAD

**Issue by LuisFellp** [fluddokt/opsu#250]
when i was playing, this message has appeared and i have no idea how to reset this, when its appear the game sync goes extremely bad

please fix it or help me

**Comment by chutchatut** [comment]
@LuisFellp same. Pixel 2 on Android P DP2.

**Comment by itdelatrisu** [comment]
Duplicate of #247.

**Comment by chutchatut** [comment]
Thanks

**Comment by fluddokt** [comment]
Should be fixed in 0.16.1a

**Comment by Benik3** [comment]
Hello.

Setting is fixed, but how to reset already set local offset? 

Thanks
