### ISSUE TITLE
No songs from the hexide network shows up!

### ISSUE THREAD

**Issue by FrogBoi** [fluddokt/opsu#262]
[Type your description here. Feel free to delete the info below if it's not relevant.]

So i was trying to download songs and i can't establish a connection to ripple and Mnetwork it has happened before so i don't think much about it but the i notice that i have a connection to hexide but no songs are showing up. Help would be greatly appreciated!---
**Version:** 0.16.0b
**OS:** nacl (x86)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 2.0 Chromium (Chromium)
BOARD: bare_metal_i686
FINGERPRINT: chromium/arc/bare_metal_i686:5.0/54.5021.629.0/54.5021.629.0:user/release-keys
HOST: build111-m7.golo.chromium.org
MODEL: App Runtime for Chrome Dev
INCREMENTAL: 54.5021.629.0
RELEASE: 5.0

**Comment by fluddokt** [comment]
Should work again in 0.16.1a
