### ISSUE TITLE
Include in the open source F-Droid appstore

### ISSUE THREAD

**Issue by UnderSampled** [fluddokt/opsu#279]
As an open source app, I'd love to see this made available through F-Droid

There are a few steps to take to make sure the apps is licensed properly, mainly configuring a version that can build and run without Google Play Services (A build flag could keep them separate).

There are many people who use F-Droid exclusively, but very few good games on the platform, so you would be a very welcome addition.

https://f-droid.org/docs/Inclusion_Policy/?title=Inclusion_Policy

**Comment by UnderSampled** [comment]
Correction: This app does not use Google Play Services, so that is not an issue. However, there is currently a binary copy of "jlayerOpsu1.0.2.jar", which will have to be built from source.

**Comment by rugk** [comment]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

**Comment by UnderSampled** [comment]
I helped get it onto F-Droid years ago! It has not been maintaned any since then though, so I recommend switching to Osu!Lazer, whoch has official support for Android. It is not on F-Droid because of it's not made in java, but is fully open source as far as I know.

**Comment by rugk** [comment]
Okay.

> It is not on F-Droid because of it's not made in java, but is fully open source as far as I know.

That's actually not the reason, the current blocker [seems to be a proprietary library of them](https://github.com/ppy/osu/discussions/13593#discussioncomment-1026196).
