### ISSUE TITLE
Video Playback??

### ISSUE THREAD

**Issue by rust2** [fluddokt/opsu#299]
@fluddokt @itdelatrisu @fishporange @UnderSampled, how to enable video playback? I seen the option "Video = false" in opsu.cfg and changed it to "true", but nothing changed. What i should to do?

_Originally posted by @rust2 in https://github.com/fluddokt/opsu/issues/275#issuecomment-564070158_

**Comment by UnderSampled** [comment]
The Android port has to provide platform compatible media implementations for things that work on the desktop. When @fluddokt graciously figured out how to do all that, he did not have a working solution for video. So the short answer is that video is not supported on Android with the latest version. I can help get it into F-Droid if you made a pull request here, but I haven't touched any of the actual functionality.

https://github.com/fluddokt/opsu/issues/210

**Comment by rust2** [comment]
@UnderSampled, thanks for reply.

Do you know why some of hitsounds isn't playing? In a lot of beatmaps all is working, but in some of them this issue appears

**Comment by rust2** [comment]
@UnderSampled, thanks for reply.

Do you know why some of hitsounds isn't playing? In a lot of beatmaps all is working, but in some of them this issue appears
