### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Noellelivinggayness** [fluddokt/opsu#344]
there no online scoreboard and beatmap video in my end

---
**Version:** 0.16.1a
**OS:**  miui android 10
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 build 1.11@5425693 (Imagination Technologies)
BOARD: angelica
FINGERPRINT: Redmi/angelica_eea/angelica:10/QP1A.190711.020/V12.0.11.0.QCREUXM:user/release-keys
HOST: c4-miui-ota-bd111.bj
MODEL: M2006C3MG
INCREMENTAL: V12.0.11.0.QCREUXM
RELEASE: 10
DOWNLOADED FROM: F-Droid

**Comment by CloneWith** [comment]
This version of opsu! on Android doesn't support online scoreboard and videos.

I remember and older version of opsu! (on Google Play) supports scoreboards. Only desktop versions support video playing.

**Comment by Noellelivinggayness** [comment]
> This version of opsu! on Android doesn't support online scoreboard and videos.
> 
> I remember and older version of opsu! (on Google Play) supports scoreboards. Only desktop versions support video playing.

video playing is supported but causes bugs when going over a map with a video and not playing the map
