### ISSUE TITLE
how to start a game

### ISSUE THREAD

**Issue by thymaro** [fluddokt/opsu#348]
I feel dumb, but I don't seem too be able too start a game. When I tap on play, I am prompted to download beat maps. When those are downloaded, nothing else exciting happens. When I go back to the splash screen and try again with tapping play, I get back to downloading beat maps. I'm sorry for posting this on issues, but I guess there could be an improvement to guide the user as to what to do next when the beat maps have been downloaded.

---
**Version:** 0.16.1a
**OS:** Linux (armv8l)
**JRE:** The Android Project 0
**OpenGL version:** OpenGL ES 3.2 V@0502.0 (GIT@015159c, Idb46f6465a, 1619423694) (Date:04/26/21) (Qualcomm)
BOARD: sdm660
FINGERPRINT: Cat/S62Pro/S62Pro:11/RKQ1.210406.002/1.018.00:user/release-keys
HOST: vBuild1BT72
MODEL: S62 Pro
INCREMENTAL: 1.018.00
RELEASE: 11

**Comment by ZuWah** [comment]
You need to import map after download.
![IMG_20220812_143136](https://user-images.githubusercontent.com/111113447/184306856-bca18ca0-b2a9-42b5-81be-ad8696aa7cd6.jpg)
After that, you can play all you've been downloaded.
Have fun!
