### ISSUE TITLE
Opsu problems on the first startup and the other startips and flashlight mod graphic bug

### ISSUE THREAD

**Issue by sianoivan** [fluddokt/opsu#35]
I'm having problem on a tablet lenovo a-3500h, with android version 4.4.2. When i open the game, it simply doesn't load and gets me stuck with black screen.Edit: now it works but on the first startup it makes 1 minute to open game and gave me this error.
![screenshot_2015-12-02-15-25-56](https://cloud.githubusercontent.com/assets/16105904/11533633/02baf526-990b-11e5-94ba-64da947e6cc1.png)
I also got this bug after the first startup
![screenshot_2015-12-02-15-36-51](https://cloud.githubusercontent.com/assets/16105904/11533690/533db7d6-990b-11e5-816f-6625928a700b.png)
When I do a beatmap with flashlight mod, the sliders are graphically glitched.
![screenshot_2015-12-02-16-22-42](https://cloud.githubusercontent.com/assets/16105904/11534900/8da5c1f6-9911-11e5-80c8-75ac480f2412.png)
Sometimes it happens, if you pause the game when several sliders that are coming, the slider gets invisible and the next one becomes matt.
![screenshot_2015-12-03-16-27-34](https://cloud.githubusercontent.com/assets/16105904/11564856/af78391a-99db-11e5-886b-96cb5dc1a1ae.png)

**Comment by fluddokt** [comment]
Startup I don't know.
Flashlight should be fixed in 0.13.0a.
