### ISSUE TITLE
[Feature Request] Reverse Arrow,And Slider followcircle

### ISSUE THREAD

**Issue by honard** [fluddokt/opsu#40]
the reverse arrow Bumps that follows the Beat of the song while in-game playing
then when the slider circle hits the reverse arrow it bursts

about the slider followcircle
when u hit the slider start of a slider the slider followcircle appears with a soft kinetic movement then when the slider finished the slider followcircle will shrink until it fits the bursted slider end circle

**Comment by itdelatrisu** [comment]
(resolved in https://github.com/itdelatrisu/opsu/issues/167)
