### ISSUE TITLE
opsu-android froze when starting map at first launch

### ISSUE THREAD

**Issue by chong601** [fluddokt/opsu#6]
When opsu-android is freshly loaded, it hangs a while after selected a beatmap to play (about 5-10 seconds).
However, subsequent load no longer contain the hang.

**Comment by fluddokt** [comment]
This was recently changed in opsu to load images before a game.
6cd6938ea542fef05a9510d2a52e9742632e7879

Should I undo this undo for this port?

**Comment by itdelatrisu** [comment]
I moved image loading to before a game instead of at startup.  You'll have the same delay at one time or the other, so... yeah.  I don't know which would be better.

**Comment by chong601** [comment]
I personally haven't tested the PC version yet, so I can't give the answer...
But I think reverting will be the best solution. 

Extra info:
It seems that opsu-android runs these independently...
When it hangs to load the images before the gameplay, the gameplay already started on maps that start instantly, so by the time it finished loading, the game already started.
(Found this by doing USB debugging just now)

**Comment by fluddokt** [comment]
Well the images aren't loaded in a thread.
The only thing I can see is that the loading will pretty much kill the lead in time
as that is based on the delta time between frames.

**Comment by chong601** [comment]
Probable solutions I can think of:
1) revert it for this port
2) sleep the gameplay thread (but continue rendering by putting a loading screen) and load the images in another thread and wake the gameplay thread up

**Comment by itdelatrisu** [comment]
Images can't be loaded in another thread due to the nature of OpenGL (or, it's extremely difficult to do so).  Is it so much of a problem?  (I personally prefer shorter startup times, though I see why you'd disagree. :P)

**Comment by chong601** [comment]
personally, i don't get bothered with hangs on gaming (considering this is a prerelease and it isn't fully optimized yet) but when it is reproducible easily on first run, it just tops my OCD level of debugging xD
