### ISSUE TITLE
opsu-android bricks when a non-word or number key is pressed

### ISSUE THREAD

**Issue by chong601** [fluddokt/opsu#7]
When pressed keys other than characters or numbers, opsu-android will stop responding (it just hangs).
Affects: 0.7.0a (earlier versions may be affected as well since opsu! supports keyboard input too)

Keys that make opsu-android hang:
Esc, Home, End (probably more to come, not completely tested yet).

**Comment by fluddokt** [comment]
Does this happen in every screen?
What are you using to press those keys?

**Comment by chong601** [comment]
I haven't completely tested it yet but it immediately hangs when i pressed Esc during gameplay and it also hangs when i accidentally pressed Home key rather than Backspace key during downloading maps.

I use a standard PC keyboard (104-key) using the USB-On-the-Go feature available on my Android tablet (Lenovo A7-30 A3300-HV Android 4.4.2)

**Comment by fluddokt** [comment]
I'm guessing this was caused by 
com.badlogic.gdx.Input.Keys.toString(keycode).charAt(0)
in StateBasedGame and I removed it some time ago, so it should at least not brick anymore.
