### ISSUE TITLE
opsu-android UI doesn't scale well with high-res screen

### ISSUE THREAD

**Issue by chong601** [fluddokt/opsu#8]
Tested on Samsung Galaxy Tab 4 8.0 (Android 4.4.2) and Samsung Galaxy Note 4 (Android 4.4.2).
Both iirc have more than 1080p.

(unfortunately no screenshot available because didn't find the method to get one D:)

**Comment by fluddokt** [comment]
Can I get a better description of what doesn't scale well?
images too big / small?
Images are in the wrong locations?
Fonts looks screwed up?
The play and exit button too big/small?

**Comment by chong601** [comment]
I will try to get a screenshot later... kind of hard to explain since i don't own those phones (tested at those telco stores)
On the main menu, the opsu! logo is in the right size, but the play and exit button is not scaled to the right size (gets extremely large)
On any screen, words are really tiny (i think 6 pixels tall?)
Also, on those phones, rendering is kind of screwed up (comboburst works slower than normal devices) but everything else is kind of fine

**Comment by chong601** [comment]
Some screenshots I have obtained from some phones:
Sony Xperia Z (1080p resolution):
Average: 59 FPS
![Main menu](http://puu.sh/gxHIf.png)
![Options screen](http://puu.sh/gxHJ4.png)

Xiaomi Redmi Note LTE (720p resolution)
Average: 54 FPS (due to unknown reasons)
![Main menu](http://puu.sh/gxIER.png)
![Options screen](http://puu.sh/gxIFV.png)
Notes:
- Lags after some play (disabled all effects) randomly spiking at 24-59 FPS
- Gets extremely hot after 2-3 plays

My best guess for this issue is the resolution that gets the main-menu rendering go wrong

**Comment by itdelatrisu** [comment]
What's wrong in the screenshots?  They look fine to me...

**Comment by chong601** [comment]
If you open the image to new tab, you will see some difference for example text in options is larger than Redmi Note LTE than Xperia Z due to resolution difference, the play and exit button size is different as well.

Most of the UI issues I have encountered are actually not really an issue but on Note 4 Edge and some latest Samsung flagship phone (which I forgot to get a screenshot yesterday even if I am able to have a hold on it longer than other phone, will try to get one today if I remember), the play and exit button is **WAY** larger than the size of opsu! logo.

Also, I do find out opsu! runs way smoother on cheap phones rather than expensive ones LOL...

**Comment by chong601** [comment]
Tested on Note 4 Edge (this have a 2560*1600 resolution)
![Main menu](http://puu.sh/gyxtR.png)
![Options](http://puu.sh/gyxhU.png)
Notes: Lags on spinner, suffers from stuttering probably due to overheating

OT: i'm suprised that opsu! still look great even on this resolution :+1:

**Comment by fluddokt** [comment]
Most of the scaling issues should be fixed by next release
