### ISSUE TITLE
Repository access

### ISSUE THREAD

**Issue by itdelatrisu** [fluddokt/opsu#81]
I realized I'm not able to make any pull requests since I can't fork a fork of my own repository... do you mind giving me repository access (maybe to a separate branch)?

Here's a diff of the really minor changes I was trying to make, if you want to just commit it yourself: http://pastebin.com/raw/xvRy3JnH (just small tweaks)

I also sent you a PM on the osu! forums. :)

**Comment by fluddokt** [comment]
Uhh I don't know how. I added you as a Collaborator, does that work?

**Comment by itdelatrisu** [comment]
Yup, got it -- thanks!
